[package]
name = "quick_tag"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audiotags = "0.4.1"
id3 = "1.3.0"
serde = "1.0.145"
serde_derive = "1.0.145"
toml = "0.5.9"
